name: dream_analysis_flutter
description: "dream analysis with AI where AI can analyse the human dreams"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.6.1
  dio: ^5.4.0
  json_annotation: ^4.8.1

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2

  share_plus: ^10.1.2
  url_launcher: ^6.3.1

  uuid: ^4.5.1
  intl: ^0.19.0

  flutter_svg: ^2.0.10
  shimmer: ^3.0.0
  lottie: ^3.1.2

  go_router: ^14.6.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

  # ðŸ”¥ Splash Screen (COLOR ONLY)
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/

# ðŸ”¥ Native Splash Configuration (NO IMAGE)
flutter_native_splash:
  color: "#0E0D34"

  android_12:
    color: "#0E0D34"

# App Icon Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  #adaptive_icon_background: "#3d3667"
  adaptive_icon_background: "#fffff"
  adaptive_icon_foreground: "assets/icon/icon.png"
  adaptive_icon_foreground_inset: 16
